# Inverse Cosserat Model

In [22]:
# Setup
import numpy as np
import json
import matplotlib.pyplot as plt

# Importing data
with open("2.5N_run5.json") as json_file:
    data = json.load(json_file)

data = data["data"]

curvatures = data[0]['curvatures'][10:18]

# Functions
def skew_symmetric(vector):

    skew_matrix = np.zeros((3,3))

    skew_matrix = np.array([[0, -vector[2][0], vector[1][0]], 
                            [vector[2][0], 0, -vector[0][0]],
                            [-vector[1][0], vector[0][0], 0]],dtype='object')
    return skew_matrix

[[0 -3.0 2.0]
 [3.0 0 -1.0]
 [-2.0 1.0 0]]


### Defining Constants

In [ ]:
kappa = curvatures
theta_b = 

r = 

Ixx = 0.25*np.pi*(r^4)
Iyy = Ixx
Izz = 2*Ixx

J = np.diag([Ixx,Iyy,Izz])

G = 
E = 
A = np.pi*r^2

# Shear and axial stiffness matrix
Kv = np.diag([G*A,G*A,E*A])
# Bending and torsional stiffness matix
Ku = np.diag([E,E,G])*J

# From Assumptions
v_0 = [[0],[0],[1]]

u = np.zeros((3,1))
u[0] = kappa*np.cos(theta_b)
u[1] = kappa*np.sin(theta_b)

uhat = skew_symmetric(u)

### Equilibrium Equations

In [ ]:
dnds = -uhat*n - f;
dmds = -uhat*m - vhat*n - l;

### Constitutive Equations

In [ ]:
v = np.linalg.inv(Kv)*n + v_0
u = np.linalg.inv(Ku)*m + u_0